internal/extender/resource.go

Fixes: https://github.com/palantir/k8s-spark-scheduler/issues/2
Should allow us to troubleshoot binpacking issues more easily.

add more verbose logging when binpacking drivers

---

.gitignore

not ignoring artifacts changes the `git describe --tags` output, failing `docker save`

fix publish

---

internal/extender/resource.go

When a spark application has executors that crash, those executors remain bound to their reservation. In the case where all executors are lost, this leads to a starved spark application which appears to be healthy, but is unable to request new executors.
This fix allows a new scheduling request to take a reservation if it is bound to a terminated pod.

Fix: release reservations for terminated pods

---

cmd/server.go
internal/extender/resource.go

Wraps the scheduler informer and other background goroutines with the fatal logging handler to get more insights in case of panics

Informer goroutine fatal logging

---

internal/extender/resource.go

Adds a check for existing resource reservation for a driver before we attempt to schedule it in case we get a double submission from `kube-scheduler`.
We currently try to binpack a second time and only if the driver fits do we return the previous resource reservation's node, but we create a duplicate demand if the driver does not fit. This PR makes the behavior consistent between the two cases, and reduces the chances of double creating demands.

[Fix] Check if resource reservation already exists before fitting driver

---

cmd/server.go
internal/cache/safedemands.go
internal/extender/extendertest/extender_test_utils.go

The `sharedInformerFactory.Start()` method loops over its internal `informers` map when called and calls `Run()` on each informer that hasn't been started yet. An informer is effectively created and added to the factory's `informers` map when its `Informer()` or `Lister()` methods are invoked and not on initialization.
This PR makes sure we create the needed informers before starting the factories so we avoid entering into race conditions when `Start()` is called in goroutines, or failures when called synchronously but in the reverse order.

[Fix] Call informer factory Start() only after creating the needed informers

---

internal/extender/failover.go

Failover now properly initializes the SoftReservationStore for all drivers that have dynamic allocation enabled and not just the ones that currently have stale executors.
PR also refactors parts of the code to separate the SoftReservation failover logic into its own method.

Fixes a bug in soft reservation failover for dynamic allocation

---

internal/extender/failover.go

Fixes a bug in failover where we were still reading the outdated resource reservation object when checking which executors need to have soft reservations.

Fixes bug in failover where we were reading the outdated resource reservation object

---

internal/extender/resource.go

Removes the demand object for an executor when scheduled if it exists, even if it is an extra executor, preventing demand leaks.
The scenario that this PR fixes is the following:
1. Executor doesn't fit, but application is under min executors, so we create demand in `rescheduleExecutor()`
2. We get a request later for the same executor but are now over the min, so we treat it as an extra executor. 
3. There is space for the executor this time so we allocate it, but don't delete the previous demand.

Removes demand object for extra executors

---

cmd/server.go
config/config.go
internal/extender/binpack.go
internal/extender/extendertest/extender_test_utils.go
internal/extender/hostordering_test.go
internal/extender/resource.go

We kill our hosts regularly, and so we would like to schedule drivers so
that they heuristically get the longest remaining lifetime. For this
reason, we currently sort our hosts purely in terms of their remaining
host lifetime.
In practice, this is demonstrably wasteful. Consider the case where we
have hosts A and B, where A has a single pod running on it and we've
just booted up host B and so it has no pods running on it. An arriving
job will be scheduled onto host B, leading to poor usage. We would
prefer to schedule the arriving job onto A as well, and be able to kill
B.
This PR takes current usage into account. It fills up the most
utilized hosts first, getting to the near idle ones last.
The goal is that instead of having an even spread of partially used
hosts, we'd be able to …

Prioritize hosts by current usage rather than just lifetime

---

internal/extender/overhead.go
internal/extender/unschedulablepods.go

We sometimes incorrectly mark a pod as 'exceeding capacity' even though it should have been able to fit in the cluster. The reason for this is a fluctuation in the overhead calculation which appears to be due to the non-deterministic order with which resource reservations and executor pods are deleted.
Both the resource reservation object and the created executors have the driver as an owner. During garbage collection, the resource reservation object can get deleted while the executors stay around, which means that scheduler will count those as pods without reservations, i.e. overhead.
This PR only considers pods that do not have the `spark-scheduler` scheduler name when judging whether new pods would fit in an empty cluster.

Only considers non-schedulable overhead when judging if pod exceeds cluster capacity

---

internal/cache/softreservations.go

Fixes a bug in the SoftReservationStore where we were doing a recursive read lock and which could result in a deadlock.
Specifically `ExecutorHasSoftReservation` grabs a read lock but calls `GetSoftReservation` which also grabs the read lock. Given that go mutex are not reentrant, a call to `Lock()` by another goroutine in between the 2 read lock calls above would result in a deadlock.

Fixes a probable deadlock condition in the SoftReservationStore

---

Gopkg.lock
internal/cache/safedemands.go
vendor/github.com/palantir/pkg/retry/retry.go

demand informer sync should be retried on startup, else the extender can operate without creating or deleting demands until the next check for the demand crd and informer sync, which is currently after a minute

demand informer retries

---

examples/extender.yml

Hello, everyone!
When trying to run the extender locally in minikube, I was getting the following error in the extender's container:
```
Error: Failed to get CRD: customresourcedefinitions.apiextensions.k8s.io "resourcereservations.sparkscheduler.palantir.com" is forbidden: User "system:serviceaccount:spark:spark-scheduler" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```
By taking a look at the `spark-scheduler`'s `ServiceAccount` definition, I saw that it was created in the `default` namespace instead of `spark`.
Thank you,
Cosmin

[FIX] - Create extender.yaml ServiceAccount in spark namespace

---

internal/metrics/metrics.go

This is to help measure the effect of #88. We hope that after that change this number stays 1 most of the time.

Report the number of zones each application is spread across

---

cmd/server.go
internal/cache/softreservations.go
internal/common/constants.go
internal/common/utils/pods.go
internal/events/events.go
internal/extender/demand.go
internal/extender/demand_gc.go
internal/extender/failover.go
internal/extender/overhead.go
internal/extender/resource.go
internal/extender/resourcereservations.go
internal/extender/sparkpods.go
internal/extender/sparkpods_test.go
internal/extender/unschedulablepods.go

This PR introduces a background pod event handler which deletes any demand we have previously created for a pod when it gets scheduled.
This is supposed to catch any demands that were not deleted by the extender, and we can later on centralise all demand deletions in here.

Introduces DemandGC 

---

.circleci/config.yml
cmd/server.go
internal/cache/softreservations.go
internal/common/utils/pods.go
internal/common/utils/sets.go
internal/extender/extendertest/extender_test_utils.go
internal/extender/failover.go
internal/extender/resource.go
internal/extender/resource_test.go
internal/extender/resourcereservations.go

This PR refactors the way we get and create both resource reservations as well as soft reservations. The aim of this is two fold:
1. Simplify the logic in the scheduling code paths by abstracting away common functionality such as checking for unbound reservations, checking for free extra executor space, patching the reservation object, etc...
2. Introduce a common place through which all reads and writes of reservations go through which will enable us to introduce new functionality in the future
This PR does not currently include refactoring the failover code, but we should handle this in a separate PR.

Refactors Reservation creations into a ResourceReservationManager

---

internal/extender/resource.go

https://github.com/palantir/k8s-spark-scheduler/pull/116 introduced a small regression in reporting the reschedule outcome in the case of dynamic allocation executors whereby we were reporting `successRescheduled` instead of the more specific `successScheduledExtraExecutor`

Fixes the reporting of the reschedule outcome

---

cmd/server.go
internal/metrics/metrics.go
internal/metrics/waste.go

We currently emit the waste metrics as a whole, but most operations (queueing, scheduling) are done on an instance group level. This PR adds an instance group tag to the emitted metrics to differentiate any problematic instance groups from others.

Emit the scheduler waste metrics by instance group instead of a total

---

cmd/server.go
internal/extender/extendertest/extender_test_utils.go
internal/extender/resource.go
internal/metrics/waste.go

The current `after-demand-fulfilled` waste metric tracks the time it took a pod to get scheduled after a demand was fulfilled, indicating slowness somewhere in scheduler or our extender. The problem is that this dismisses other factors such as FIFO requirements where the demand might have been fulfilled, but we still can't schedule the pod due to an earlier one that was still not scheduled.
We differentiate between waste after demand fulfilled because of scheduler slowness and other scheduling failure outcomes.
This uses a best effort in-memory tracker of last failure outcome since we don't commit the result anywhere and it would not currently be worth publishing object updates for this specific metric.

Detailed after demand waste metric with failure outcomes

---

cmd/server.go
internal/extender/extendertest/extender_test_utils.go
internal/extender/failover.go
internal/extender/overhead.go
internal/extender/resourcereservations.go

Refactors the way we calculate node overhead to do the following:
* Make it dynamic in that it listens to pod informer events and updates requests on nodes accordingly rather than the current version which only recalculates the overhead every 30 seconds
* Only consider a pod as having returned its requested resources when it is deleted which is inline with the `kube-scheduler` calculation
* We also no longer fallback to the instance group median as we should now be able to accurately measure node overhead in realtime which makes the accurate calculation possible
The second point raises a potential issue: due to the fact that we were considering a pod as no longer requesting resources once it completes successfully or fails, we were undercounting overhead and were potentially …

Node Overhead Calculation Refactor

---

examples/extender.yml

the `v1.13.1` was release 2 years ago. It seems to me it is a bit out-of-date. Also, the max backoff in `v1.13.1` is 1 minute (https://github.com/kubernetes/kubernetes/blob/release-1.13/pkg/scheduler/util/backoff_utils.go#L103). That can raise scheduling latency when cluster gets enough resources (add more nodes or remove completed jobs). 
`v1.15.12` is the latest version which can accept `PodPriority=false`.

Upgrade kube-scheduler from v1.13.1 to v1.15.12

---

docker/Dockerfile
spark-scheduler-conversion-webhook/docker/Dockerfile

Upgrades base docker image from Alpine 3.7 to Alpine 3.16 for both spark-scheduler and the conversion webhook.

Upgrade base docker image version for kss and kscw to alpine 3.16

---

docker/Dockerfile
spark-scheduler-conversion-webhook/docker/Dockerfile

Reduce the size and attack surface of scheduler containers by using a base image of scratch
Tested locally on a minikube cluster

Use scratch as the base image for scheduler containers

---

cmd/server.go
config/config.go
docker/var/conf/install.yml
hack/dev/generate-certs.sh
internal/extender/extendertest/extender_test_utils.go
internal/extender/unschedulablepods.go

Pods are currently marked as "exceeds capacity" if they are unschedulable for 10 mins. This PR will make this duration configurable to account for environments where scheduler needs to wait for longer before giving up on scheduling a pod.

Make unschedulable pod timeout duration configurable

---

internal/extender/resource.go

We now log the spark app id when scheduling a pod, this makes it easier to find scheduling log lines for specific applications and makes debugging easier.
This label is always guaranteed to be set or else scheduling will fail later when we create resource reservations as the name of the resource reservation is equal to the spark-app-id label value.

Log spark app id when scheduling pod

---

internal/extender/resource.go
internal/extender/resource_test.go

The current logic just picks a random node on which the executor will fit:
https://github.com/palantir/k8s-spark-scheduler/blob/36236cf049a5c730afa5e7107eb3ef0fb624cc35/internal/extender/resource.go#L435-L442
This PR simply tries to fit the new executor in the 'fullest' node.

When scheduling dynamic executors, order nodes by usage instead of picking a node at random

---

internal/sort/nodesorting.go
internal/sort/nodesorting_test.go

All things being equal, compare node names to break ties.
Example flake: https://app.circleci.com/pipelines/github/palantir/k8s-spark-scheduler/1857/workflows/017da816-ce66-4a03-898d-36ddfbe3d850/jobs/6103
Confirmed this works by running the test in a loop:
* with current logic it yields several failures
* with this PR it's all ✅

Make node sorting deterministic as it otherwise causes flakes

---

internal/extender/binpack.go

`single-az-minimal-fragmentation` isn't single AZ
==COMMIT_MSG==
`single-az-minimal-fragmentation` only schedules in a single AZ
==COMMIT_MSG==

Point single-az-minimal-fragmentation to the correct function

---

go.mod
go.sum
vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/minimal_fragmentation.go
vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/capacity/capacity.go
vendor/modules.txt

0.15.0 includes https://github.com/palantir/k8s-spark-scheduler-lib/pull/104
==COMMIT_MSG==
Bump spark-scheduler-lib to 0.15.0
==COMMIT_MSG==

Bump spark-scheduler-lib to 0.15.0

---

internal/extender/resource.go
internal/metrics/metrics.go

We don't have a good way to quantify fragmentation. With this new metric we should be able to observe whether https://github.com/palantir/k8s-spark-scheduler-lib/pull/100 actually reduces fragmentation (this metric should go up in this case).
==COMMIT_MSG==
Report # executors / # nodes used to schedule this application
==COMMIT_MSG==
`Histogram` works with `int64`,not `float64`, either we get something a little imprecise e.g. 5 executors on 3 nodes = 5 / 3 = 1, or we need to scale the metric 100 * 5 / 3 = 166, but then this is a bit confusing as the metric doesn't report the true ratio anymore. Given that we mostly care about fragmentation of larger applications where this metric should ideally be well above 1, I went with the former approach.

Report # executors / # nodes used to schedule this application

---

internal/extender/resourcereservations.go
internal/metrics/metrics.go

#250 helps quantify how many resources are taken by unbound reservations, however it doesn't help us understand how long reservation stay unbound.
==COMMIT_MSG==
Add time to bind metrics
==COMMIT_MSG==
This doesn't capture reservations that never get bound, but that shouldn't really happen under normal circumstances.

Add time to bind metrics

---

cmd/clients.go
cmd/server.go

- Refactor server initialization to expose a plugin point to end to end tests 
- In the future we can use `InitServerWithClients` to pass through K8s clients in memory to ensure that the full server initialization works and all informers and objects jobs will be ran
==COMMIT_MSG==
==COMMIT_MSG==

improvement: Refactor server initialization to expose a plugin point to end to end tests

---

internal/extender/overhead.go
internal/extender/resource.go
internal/extender/resourcereservations.go

- Move the ResourceReservationManager to an interface downstream clients can mock it 
- Right now demand manipulation are a combination of static methods and using the raw SafeDemandCache struct which makes it impossible to test or mock
- This moves this operations behind a single interface
- Noop
- Similar to https://github.com/palantir/k8s-spark-scheduler/pull/255
==COMMIT_MSG==
==COMMIT_MSG==

improvement: Move the ResourceReservationManager to an interface downstream clients can mock it

---

cmd/server.go
internal/binpacker/binpack.go
internal/demands/demand.go
internal/demands/demand_test.go
internal/extender/demand_gc.go
internal/extender/extendertest/extender_test_utils.go
internal/extender/failover.go
internal/extender/resource.go
internal/extender/resource_test.go
internal/extender/resourcereservations.go
internal/extender/sparkpods.go
internal/extender/sparkpods_test.go
internal/extender/unschedulablepods.go
internal/extender/unschedulablepods_test.go
internal/types/const.go
internal/types/types.go

- Move the demand processing behind a single interface that can be shared 
- Right now demand manipulation are a combination of static methods and using the raw `SafeDemandCache` struct which makes it impossible to test or mock
- This moves this operations behind a single interface
- Move out `binpacker` to its own package (`binpacker`) so it can be shared
- Move the common object types into their own package (`types`) so it can be shared
==COMMIT_MSG==
==COMMIT_MSG==

improvement: Move the demand processing behind a single interface that can be shared

---

internal/extender/resourcereservations.go

- Fix semantic merge conflicts 
- Types were updated in https://github.com/palantir/k8s-spark-scheduler/pull/255
==COMMIT_MSG==
==COMMIT_MSG==

fix: Fix semantic merge conflicts
