- .gitignore
- internal/extender/demand.go
- internal/extender/resource.go
- internal/extender/sparkpods.go
- internal/extender/sparkpods_test.go
Added `sparkApplicationResources` struct which contains all resources required for a spark application
> Add sparkApplicationResources abstraction

- internal/metrics/metrics.go
Simplify counting, also change the error handling when the AZ label can't be found.
> small refactor to cross-az metrics

- internal/metrics/metrics.go
Before, we didn't consider how many pods run within the same node
> Correct AZ metric

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/apis/sparkscheduler/v1beta1/crd.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/distribute_evenly.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/pack_tightly.go
This bump brings a crd change we need to support kubernetes v1.10 clusters
> bump scheduler lib

- internal/metrics/queue.go
Pod state change metrics previously had the sample set of all running pods in the cluster. After this change the sample set would be pods that have transitioned state in the last minute.
This might miss state transitions on GC's, if it hasn't run for at least one decay threshold, but that risk already exists for short lived pods.
> decay state change metrics

- internal/extender/sparkpods.go
kube-scheduler also seems to do this https://github.com/kubernetes/kubernetes/blob/c7a8596a397f19be9641b13d807d3892d744a752/pkg/scheduler/scheduler.go#L448
> Ignore deleting pods in FIFO

- internal/extender/resource.go
> Add failure-earlier-drivers as a separate category of failures

- internal/extender/resource.go
Currently spark-scheduler creates a `demand` object only for the driver that all earlier drivers fit to the cluster, but itself can't.
On batch submissions of a large number of spark applications, this makes the demand creation slow.
With this change, scheduler treats a scheduling failure because of FIFO resource constraints the same as a failure to fit, and creates demand objects. A single scan of the pending pod queue by the scheduler will create all demand objects necessary to fit every pending pod, assuming no running pods will die
> create demand resources for fifo failures as well

- internal/cache/async.go
do not log error level if the namespace is terminating
> delete on non retryable creation failures

- internal/metrics/cache.go
we should log if the listers and the cache deviates significantly
> defensive logging

- internal/events/events.go
This wasn't working correctly and i believe that is because the creationTime was not being set
> Add demand creation timestamp to the demand_deleted event.

- Gopkg.lock
- Gopkg.toml
- internal/extender/binpack.go
- internal/extender/nodesorting.go
- internal/extender/nodesorting_test.go
- internal/extender/resource.go
- internal/extender/unschedulablepods.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/az_aware_pack_tightly.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/binpack.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/distribute_evenly.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/pack_tightly.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/resources/resources.go
A preview of the changes that would we needed after merging https://github.com/palantir/k8s-spark-scheduler-lib/pull/15
> Upgrade to new version of k8s-spark-scheduler-lib

- cmd/server.go
- internal/metrics/informer.go
- internal/metrics/metrics.go
Best effort metric for informer delays.
> pod informer delay metrics

- internal/metrics/queue.go
This PR adds some additional information about any detected stuck pods such as the last state change time to help debug any of those issues.
> Adds more information to the stuck pod log to aid in investigations

- cmd/server.go
- config/config.go
- internal/extender/extendertest/extender_test_utils.go
- internal/extender/resource.go
Introduces a new configurable FIFO feature which allows us to skip a driver from blocking the fifo queue if its age is less than the configurable time.
> Feature: Flexible Fifo

- README.md
- examples/driver.template.yml
> Correct the driver.yaml in readme

- go.mod
- go.sum
- internal/extender/binpack.go
- internal/extender/resource.go
- internal/extender/unschedulablepods.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/az_aware_pack_tightly.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/binpack.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/distribute_evenly.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/efficiency.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/minimal_fragmentation.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/pack_tightly.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/single_az.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/single_az_minimal_fragmentation.go
- vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/resources/resources.go
- vendor/modules.txt
See https://github.com/palantir/k8s-spark-scheduler-lib/pull/100 for context
> Add new single-az-minimal-fragmentation function

- internal/extender/resource.go
- internal/metrics/metrics.go
Add metric to show which zone we're failing to schedule in for additional executors
> Add metric to show which zone we're failing to schedule in for additional executors

- internal/extender/binpack.go
- internal/extender/demand.go
- internal/extender/resource.go
==COMMIT_MSG==
Explictly encode which BinPacker are single AZ
==COMMIT_MSG==
> Explictly encode which BinPacker are single AZ

- internal/extender/resource.go
- internal/metrics/binpack.go
- internal/metrics/metrics.go
Instance group was not included with the metric.
==COMMIT_MSG==
==COMMIT_MSG==
> Include instance group in the metrics

- internal/extender/resource.go
- internal/metrics/metrics.go
==COMMIT_MSG==
Add driver/executor collocation metric
==COMMIT_MSG==
> Add driver/executor collocation metric
